export const GET_ALL_PATIENTS = "GET_ALL_PATIENTS";
export const GET_ALL_PATIENTS_SUCCESS = "GET_ALL_PATIENTS_SUCCESS";
export const GET_ALL_PATIENTS_ERROR = "GET_ALL_PATIENTS_ERROR";

export const GET_PATIENT_RECORDS = "GET_PATIENT_RECORDS";
export const GET_PATIENT_RECORDS_SUCCESS = "GET_PATIENT_RECORDS_SUCCESS";
export const GET_PATIENT_RECORDS_ERROR = "GET_PATIENT_RECORDS_ERROR";
